# Generated by Django 4.0.4 on 2022-04-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplar', '0003_priloha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priloha',
            options={'verbose_name': 'Příloha', 'verbose_name_plural': 'Přílohy'},
        ),
    ]
