# Generated by Django 4.0.4 on 2022-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplar', '0005_remove_exemplar_datum_vytvoreni'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Poster'),
        ),
    ]
